import type { Metadata } from "next";
import { Outfit, UnifrakturMaguntia } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import { Toaster } from "@/components/ui/sonner"

const outfit = Outfit({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-outfit',
});

const gothicFont = UnifrakturMaguntia({
    weight: "400", // This font only supports weight 400
    subsets: ["latin"],
    variable: "--font-gothic", // Define the CSS variable
    display: "swap",
});
export const metadata: Metadata = {
    title: "Chat App",
    description: "Generated by @Okoyep98",

};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>

            <html lang="en">
                <body
                    className={`${outfit.className} ${gothicFont.variable} antialiased min-h-screen`}
                >
                    {/* <SignedOut>
                        <SignInButton />
                        <SignUpButton>
                            <button className="bg-[#6c47ff] text-ceramic-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                                Sign Up
                            </button>
                        </SignUpButton>
                    </SignedOut>
                    <SignedIn>
                        <UserButton />
                    </SignedIn> */}
                    {children}
                    <Toaster />
                </body>
            </html>
        </ClerkProvider>
    );
}
