import type { Metadata } from "next";
import { Outfit, UnifrakturMaguntia } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/providers/QueryProvider";
import { Toaster } from "@/components/ui/sonner"

const outfit = Outfit({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-outfit',
});

const gothicFont = UnifrakturMaguntia({
    weight: "400", // This font only supports weight 400
    subsets: ["latin"],
    variable: "--font-gothic", // Define the CSS variable
    display: "swap",
});
export const metadata: Metadata = {
    title: "Chat App",
    description: "Generated by @Okoyep98",

};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <html lang="en">
            <body
                className={`${outfit.className} ${gothicFont.variable} antialiased min-h-screen`}
            >
                <QueryProvider>
                    {children}
                    <Toaster position="top-right" />
                </QueryProvider>
            </body>
        </html>
    );
}
